spring:
  application:
    name: spring-data

  datasource:
    url: jdbc:postgresql://localhost:5432/app_db?currentSchema=app
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    liquibase-schema: app

server:
  port: 8081