version: '3.8'

services:

  service_db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  service_app:
    build:
      context: ../
      dockerfile: Dockerfile
    volumes:
      - ../target:/app_jar
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service_db/app_db
    depends_on:
      - service_db
    restart: on-failure